version: "3"

services:

  backend:

    build: ./backend

    ports:
      - "8000:8000"


  database:

    image: postgres

    environment:

      POSTGRES_USER: admin

      POSTGRES_PASSWORD: password

      POSTGRES_DB: applications

    ports:

      - "5432:5432"
